spring.application.name=bayou-thrid-party
alibaba.cloud.access-key=LTAI5t7bxvcBX9zbbqnXrHj2
alibaba.cloud.secret-key=t2jX1DYieiQzoJ4uyac9CgMo2VcvC5
alibaba.cloud.oss.endpoint=oss-cn-chengdu.aliyuncs.com
#spring.cloud.alicloud.access-key=LTAI5t7bxvcBX9zbbqnXrHj2
#spring.cloud.alicloud.secret-key=t2jX1DYieiQzoJ4uyac9CgMo2VcvC5
#spring.cloud.alicloud.oss.endpoint=oss-cn-chengdu.aliyuncs.com